---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cm-configuration-role
  namespace: test1
rules:
  - apiGroups: [""]
    resources: ["configmaps","secrets"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cm-create-configmaps
  namespace: test2
rules:
  - apiGroups: [""]
    resources: ["configmaps","secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cm-configuration-role-binding
  namespace: test1
subjects:
  - kind: ServiceAccount
    name: golang-sc
    namespace: test2
roleRef:
  kind: Role
  name: cm-configuration-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cm-configuration-role-binding2
  namespace: test2
subjects:
  - kind: ServiceAccount
    name: golang-sc
    namespace: test2
roleRef:
  kind: Role
  name: cm-create-configmaps
  apiGroup: rbac.authorization.k8s.io